name: ReactJs CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "reactjs/**"
      - ".github/workflows/**"

jobs:
  checks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: reactjs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      
      - name: Setup NodeJs
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: reactjs/package-lock.json

      - name: Install Project Dependencies
        run: npm ci

      - name: Check Formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit Tests
        run: npm test

      - name: Build
        run: npm run build